spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/final_quiz_db?characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true